### ISSUE TITLE
Build Fails (0.4-rc2, Mac OS X)

### ISSUE THREAD

**Issue by cortner** [JuliaLang/Gtk.jl#186]
Build of Gtk currently fails; see also [julia-users](https://groups.google.com/forum/#!topic/julia-users/WUx25Gm74bU)

From a clean v0.4 directory I get the following:

$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-rc2 (2015-09-18 17:51 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.add("Gtk")
INFO: Initializing package repository /Users/ortner/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Installing BinDeps v0.3.17
INFO: Installing Cairo v0.2.31
INFO: Installing ColorTypes v0.1.6
INFO: Installing Colors v0.5.4
INFO: Installing Compat v0.7.3
INFO: Installing Docile v0.5.19
INFO: Installing FixedPointNumbers v0.0.11
INFO: Installing Graphics v0.1.3
INFO: Installing Gtk v0.9.2
INFO: Installing Homebrew v0.1.16
INFO: Installing HttpCommon v0.2.4
INFO: Installing JSON v0.4.6
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.1.2
INFO: Installing URIParser v0.1.0
INFO: Building Homebrew
.
.  (many lines of compile messages)
.
INFO: Building Gtk                                                                        ==> Installing gtk+3 from staticfloat/homebrew-juliadepsError: Operation already in progress for pkg-configAnother active Homebrew process is already using pkg-config.Please wait for it to finish or terminate it to continue.==========================================================[ ERROR: Gtk ]==========================================================LoadError: failed process: Process(`/Users/ortner/.julia/v0.4/Homebrew/deps/usr/bin/brew install --force-bottle staticfloat/juliadeps/gtk+3`, ProcessExited(1)) [1]
while loading /Users/ortner/.julia/v0.4/Gtk/deps/build.jl, in expression starting on line 58

==================================================================================================================================

=========================================================[ BUILD ERRORS ]=========================================================

WARNING: Gtk had build errors.

 - packages with build errors remain installed in /Users/ortner/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Gtk")`
 - build a single package by running its `deps/build.jl` script

==================================================================================================================================
INFO: Package database updated

julia>

Let me know if I can provide additional info.

**Comment by cortner** [comment]
forgot to CC @staticfloat

**Comment by staticfloat** [comment]
Please Pkg.update() and try again. An issue similar to this one was fixed within the last two days.

**Comment by cortner** [comment]
Sorry, no luck; see output below

```
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of Nettle...
INFO: Computing changes...
INFO: Upgrading Nettle: v0.1.10 => v0.2.0
INFO: Building Homebrew
HEAD is now at a591d86 Tor 0.2.7.3-rc (devel)
HEAD is now at 1b584ee We definitely need gnome-icon-theme
INFO: Building Nettle

julia> Pkg.build("Gtk")
INFO: Building Homebrew
HEAD is now at a591d86 Tor 0.2.7.3-rc (devel)
HEAD is now at 1b584ee We definitely need gnome-icon-theme
INFO: Building Cairo
INFO: Building Gtk
==> Installing gtk+3 from staticfloat/homebrew-juliadeps
Error: Operation already in progress for pkg-config
Another active Homebrew process is already using pkg-config.
Please wait for it to finish or terminate it to continue.
==========================================================[ ERROR: Gtk ]==========================================================

LoadError: failed process: Process(`/Users/ortner/.julia/v0.4/Homebrew/deps/usr/bin/brew install --force-bottle staticfloat/juliadeps/gtk+3`, ProcessExited(1)) [1]
while loading /Users/ortner/.julia/v0.4/Gtk/deps/build.jl, in expression starting on line 58

==================================================================================================================================

=========================================================[ BUILD ERRORS ]=========================================================

WARNING: Gtk had build errors.

 - packages with build errors remain installed in /Users/ortner/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Gtk")`
 - build a single package by running its `deps/build.jl` script

==================================================================================================================================
```

**Comment by vtjnash** [comment]
This appears to be Homebrew bug https://github.com/Homebrew/homebrew/issues/17730

**Comment by staticfloat** [comment]
This happens when a two dependencies of a top-level package have dependencies themselves that are of the same name, but not coming from the same tap.  In this case, it was because I had just introduced the `gnome-icon-theme` dependency to `gtk+3` (which already depends on `staticfloat/juliadeps/pkg-config`, but `gnome-icon-theme` itself depends on `pkg-config`.  Therefore, I had to copy `gnome-icon-theme` over to `staticfloat/juliadeps`, and change its `pkg-config` dependency to `staticfloat/juliadeps/pkg-config`.  This [should be fixed now](https://github.com/staticfloat/homebrew-juliadeps/commit/b359d090888a26fb725adfc1948dc4e99e1307b8), please `Pkg.update()` and try again.

**Comment by cortner** [comment]
still doesn't work for me.

**Comment by cortner** [comment]
I can do a more careful check later and send outputs, etc.

**Comment by staticfloat** [comment]
Yes, that would be helpful.  Thanks.

**Comment by semmottos** [comment]
Hi!

I'm the OP of this issue at julia-users. I just tried Pkg.add("Gtk") again and it still doesn't succeed but for a different reason. I hope I could be of more use but I honestly don't know enough of things happening while the add operation is going on. I'm just an astonished spectator. But here's what I get:

Last login: Sun Sep 27 22:28:11 on ttys003
Jussis-MacBook-Air:~ IsoPomo$ exec '/Applications/Julia-0.4.0.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-rc2 (2015-09-18 17:51 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.status()
No packages installed

julia> Pkg.add("Gtk")
INFO: Installing BinDeps v0.3.17
INFO: Installing Cairo v0.2.31
INFO: Installing ColorTypes v0.1.6
INFO: Installing Colors v0.5.4
INFO: Installing Compat v0.7.3
INFO: Installing Docile v0.5.19
INFO: Installing FixedPointNumbers v0.0.11
INFO: Installing Graphics v0.1.3
INFO: Installing Gtk v0.9.2
INFO: Installing Homebrew v0.1.16
INFO: Installing HttpCommon v0.2.4
INFO: Installing JSON v0.4.6
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.1.2
INFO: Installing URIParser v0.1.0
INFO: Building Homebrew
remote: Counting objects: 55, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 55 (delta 42), reused 40 (delta 27), pack-reused 0
Unpacking objects: 100% (55/55), done.
From https://github.com/Homebrew/homebrew
   a591d86..433aa72  master     -> origin/master
HEAD is now at 433aa72 pyqt: update 4.11.3_1 bottle.
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 2), reused 4 (delta 2), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/staticfloat/homebrew-juliadeps
   1b584ee..b359d09  master     -> origin/master
HEAD is now at b359d09 gnome-icon-theme needs to be mirrored by us to avoid pkg-config problems
INFO: Building Cairo
INFO: Building Gtk
==> Installing gtk+3 from staticfloat/homebrew-juliadeps
==> Installing dependencies for staticfloat/juliadeps/gtk+3: jpeg, libtif
==> Installing staticfloat/juliadeps/gtk+3 dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.yosemite.bottle.2.t
Already downloaded: /Users/IsoPomo/Library/Caches/Homebrew.jl/jpeg-8d.yosemite.bottle.2.tar.gz
==> Pouring jpeg-8d.yosemite.bottle.2.tar.gz
🍺  /Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/Cellar/jpeg/8d: 18 files, 776K
==> Installing staticfloat/juliadeps/gtk+3 dependency: libtiff
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.6.yosemite.bott
Already downloaded: /Users/IsoPomo/Library/Caches/Homebrew.jl/libtiff-4.0.6.yosemite.bottle.tar.gz
==> Pouring libtiff-4.0.6.yosemite.bottle.tar.gz
🍺  /Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/Cellar/libtiff/4.0.6: 259 files, 3.9M
==> Installing staticfloat/juliadeps/gtk+3 dependency: staticfloat/juliad
==> Downloading https://juliabottles.s3.amazonaws.com/gdk-pixbuf-2.30.8_1.yosemi
######################################################################## 100.0%
==> Pouring gdk-pixbuf-2.30.8_1.yosemite.bottle.tar.gz
==> /Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/Cellar/gdk-pixbuf/2.30.8_1/bin/
==> Caveats
Programs that require this module need to set the environment variables
  export GDK_PIXBUF_MODULEDIR="/Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders"
  export GDK_PIXBUF_MODULE_FILE="/Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
If you need to manually update the query loader cache
  /Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/Cellar/gdk-pixbuf/2.30.8_1/bin/gdk-pixbuf-query-loaders --update-cache
==> Summary
🍺  /Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/Cellar/gdk-pixbuf/2.30.8_1: 209 files, 4.3M
==> Installing staticfloat/juliadeps/gtk+3 dependency: staticfloat/juliad
==> Downloading https://juliabottles.s3.amazonaws.com/atk-2.16.0.yosemite.bottle
######################################################################## 100.0%
==> Pouring atk-2.16.0.yosemite.bottle.tar.gz
🍺  /Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/Cellar/atk/2.16.0: 205 files, 3.7M
==> Installing staticfloat/juliadeps/gtk+3 dependency: hicolor-icon-theme
==> Downloading https://homebrew.bintray.com/bottles/hicolor-icon-theme-0.15.yos
######################################################################## 100.0%
==> Pouring hicolor-icon-theme-0.15.yosemite.bottle.tar.gz
🍺  /Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/Cellar/hicolor-icon-theme/0.15: 6 files, 64K
==> Installing staticfloat/juliadeps/gtk+3 dependency: staticfloat/juliad
==> Downloading https://juliabottles.s3.amazonaws.com/gnome-icon-theme-3.16.2.1.

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "gnome-icon-theme"
Download failed: https://juliabottles.s3.amazonaws.com/gnome-icon-theme-3.16.2.1.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Installing dependencies for staticfloat/juliadeps/gnome-icon-theme: x
==> Installing staticfloat/juliadeps/gnome-icon-theme dependency: xz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.1.yosemite.bottle.ta
Already downloaded: /Users/IsoPomo/Library/Caches/Homebrew.jl/xz-5.2.1.yosemite.bottle.tar.gz
==> Pouring xz-5.2.1.yosemite.bottle.tar.gz
🍺  /Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/Cellar/xz/5.2.1: 59 files, 1.7M
==> Downloading https://download.gnome.org/sources/adwaita-icon-theme/3.16/adwai
==> Downloading from https://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.gnome.org/
######################################################################## 100.0%
==> ./configure --prefix=/Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/Cellar/gno
Last 15 lines from /Users/IsoPomo/Library/Logs/Homebrew/gnome-icon-theme/01.configure:
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for pkg-config... no
checking whether NLS is requested... yes
./configure: line 2652: intltool-update: command not found
checking for intltool >= 0.40.0...  found
configure: error: Your intltool is too old.  You need intltool 0.40.0 or later.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/staticfloat/homebrew-juliadeps/issues

=================================[ ERROR: Gtk ]=================================

LoadError: failed process: Process(`/Users/IsoPomo/.julia/v0.4/Homebrew/deps/usr/bin/brew install --force-bottle staticfloat/juliadeps/gtk+3`, ProcessExited(1)) [1]
while loading /Users/IsoPomo/.julia/v0.4/Gtk/deps/build.jl, in expression starting on line 58

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Gtk had build errors.

 - packages with build errors remain installed in /Users/IsoPomo/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Gtk")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of Gtk
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia>

**Comment by staticfloat** [comment]
Thanks, that was actually very helpful.  Try `Pkg.build()` again now.

**Comment by semmottos** [comment]
YES!!!

(Sorry this took so long. I tried Gtk in my 2 programs and had to add a
couple packages more having removed them to get a clean slate for testing
this isuue. The first test went OK but the second failed the reason being
something else than Gtk)

I did Pkg.add("Gtk") in v0.4.0-rc2 (and in v.0.3.11, but who cares :)) and
'using Gtk'. The precompile in 0.4 succeeds and all is well.

Thanks a million,

Jussi Salmela

**Comment by staticfloat** [comment]
Excellent; glad it's working for you now.  I'll wait to hear from @cortner to see if the latest fix (a file's download permission was screwed up) addresses his problems as well before closing this issue.

**Comment by cortner** [comment]
Interesting, the package doesn't update
```
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove
```
but the build is now successful. 

Just out of curiosity: why?

Many thanks for the rapid fix!

**Comment by staticfloat** [comment]
That means it was most likely the same issue as @semmottos; which was a server-side permissions issue; nothing to update locally on your computer.  Glad it's fixed!

**Comment by cortner** [comment]
ok,thanks for the clarification.
